# -*- coding: utf-8 -*-
"""ties.py: every tie, as keyframes for docs/app.js plus its words in English and Thai.

A step is (phase, state change, ms, en, th). Phases: make, hand, scis.
A state change may carry "reset": n, which starts the step from step n's state.
Canvas units: 480 x 400; a full-size bag's tip top sits at y = top, its neck runs top+38 .. top+88.
"""

CX = 240

# scissors placed under the band of a full-size bag (top 30): neck bottom y = 118, lowest turn y = 112
BELOW = {"scis": 1, "sx": 120, "sy": 122, "sa": 0, "sc": 1}
BANDONLY = {"scis": 1, "sx": 240, "sy": 190, "sa": -90, "sc": 1, "slim": 1}

TIES = [
    {
        "id": "balloon", "group": "band", "kind": "balloon",
        "en": "Balloon, locked over the tip", "th": "ถุงพอง เกี่ยวปลาย",
        "where_en": "Curry, soup, anything wet: the rice-and-curry shop bag.",
        "where_th": "แกง ต้ม ของน้ำทุกอย่าง ถุงร้านข้าวแกง",
        "base": {"g": 0, "air": 0, "level": 168, "contents": "curry"},
        "say": ("beer", "The puff is air, trapped on purpose. It keeps the food from getting squashed.",
                "ถุงพองคืออากาศที่ตั้งใจขังไว้ กันอาหารโดนบีบ"),
        "hand_en": "Roll the lock off the tip, then unwind.", "hand_th": "รูดยางเส้นที่คล้องปลายออก แล้วคลายรอบ",
        "scis_en": "Below the band, bag in the bowl.", "scis_th": "ใต้ยาง ถุงตั้งในชาม",
        "steps": [
            ("make", {}, 0, "Fill it about two-thirds. The mouth stays empty.", "ตักใส่ราวสองในสาม เหลือปากถุงว่างไว้"),
            ("make", {"g": 1, "air": 1}, 1100, "Gather the mouth in both hands, pull it taut, and close it over a pocket of air.", "รวบปากถุงด้วยสองมือ ดึงให้ตึง แล้วปิดโดยขังอากาศไว้ข้างใน"),
            ("make", {"twist": 1, "arrows": "twist"}, 900, "Twist the neck a few turns. The twist holds the air in.", "บิดคอถุงสองสามรอบ เกลียวนี้ขังอากาศไว้"),
            ("make", {"finger": 1, "wraps": 0.3, "arrows": ""}, 700, "Hook one end of the rubber band on a finger and stretch it round the neck.", "คล้องหนังยางปลายหนึ่งไว้ที่นิ้ว ดึงยืดอ้อมคอถุง"),
            ("make", {"wraps": 4, "finger": 0, "arrows": "spin"}, 2000, "Three or four turns, each one above the last. Some sellers walk the band round the neck; some hold the band and turn the bag.", "พันสามสี่รอบ รอบใหม่ขึ้นไปเหนือรอบเก่า บางร้านพันยางรอบคอ บางร้านจับยางไว้แล้วหมุนถุง"),
            ("make", {"lock": 1, "arrows": ""}, 1400, "Last turn: stretch the band up over the tip and let it close on the neck. It locks the turns under it.", "รอบสุดท้าย ดึงยางข้ามปลายถุงแล้วปล่อยลงรัดคอ รอบนี้ล็อกรอบข้างล่างไว้"),
            ("hand", {"lock": 2, "arrows": "up"}, 1300, "Find the turn that runs over the tip. Roll it up and off the tip.", "หายางรอบที่คล้องข้ามปลายถุง รูดขึ้นแล้วหลุดออกทางปลาย"),
            ("hand", {"wraps": 0, "arrows": "unspin"}, 1600, "The rest unwind. Turn the bag back the other way, or walk the band off turn by turn.", "รอบที่เหลือคลายออก หมุนถุงกลับทาง หรือแกะยางออกทีละรอบ"),
            ("hand", {"twist": 0, "arrows": ""}, 800, "Untwist the neck. Keep it upright: it is full of hot curry.", "คลายเกลียวคอถุง ตั้งถุงไว้ตรงๆ ข้างในคือแกงร้อน"),
            ("scis", {"reset": 5, "bowl": 1}, 800, "Scissors: stand the bag in the bowl first.", "ใช้กรรไกร ตั้งถุงในชามก่อน"),
            ("scis", dict(BELOW), 900, "Kitchen scissors, blades open, about 1 cm below the lowest turn of band, across the twisted neck.", "กรรไกรครัว อ้าใบไว้ ต่ำกว่ายางรอบล่างสุดราว 1 ซม. ขวางคอถุงที่บิดไว้"),
            ("scis", {"sc": 0}, 500, "One snip, straight across. Hold the neck below the cut so the bag stays standing.", "ตัดฉับเดียวตรงๆ จับคอถุงใต้รอยตัดไว้ให้ถุงตั้งอยู่"),
            ("scis", {"sever": 1, "scis": 0}, 1000, "Tip, twist and band come off in one piece. Pour.", "ปลาย เกลียว และยาง หลุดออกเป็นชิ้นเดียว เทได้เลย"),
        ],
    },
    {
        "id": "flatfold", "group": "band", "kind": "balloon",
        "en": "Folded mouth, little-finger knot", "th": "พับปากถุง เกี่ยวนิ้วก้อย",
        "where_en": "Curry and soup, the way Krua Khun Toi teaches it.",
        "where_th": "แกงและต้ม ตามวิธีที่ครัวคุณต๋อยสอน",
        "base": {"g": 0, "air": 0, "level": 168, "contents": "tomyum", "tab": 1},
        "say": ("nan", "The tuck! The tucked end is the handle you pull to open it!", "ปลายที่เหน็บไว้! นั่นแหละที่ดึงเปิด!"),
        "hand_en": "Pull the band's tucked end; the knot lets go.", "hand_th": "ดึงปลายยางที่เหน็บไว้ ปมก็คลาย",
        "scis_en": "Below the band, bag in the bowl.", "scis_th": "ใต้ยาง ถุงตั้งในชาม",
        "steps": [
            ("make", {}, 0, "One bag, one rubber band.", "ถุงหนึ่งใบ หนังยางหนึ่งเส้น"),
            ("make", {"taut": 1, "arrows": "out"}, 800, "Grip both sides of the mouth and pull it tight.", "จับปากถุงสองข้าง ดึงให้ตึง"),
            ("make", {"folds": 2, "arrows": ""}, 1200, "Fold the mouth down, twice.", "พับปากถุงลงสองทบ"),
            ("make", {"g": 1, "air": 1, "taut": 0}, 1200, "Fold the left and right sides in to the middle. The folds trap the air, and the bag puffs.", "พับปากถุงข้างซ้ายข้างขวาเข้าหากลาง ขังอากาศไว้ ถุงจะพอง"),
            ("make", {"finger": 1, "wraps": 1}, 1100, "Hook the band on your little finger and take it once round the folded mouth.", "เกี่ยวหนังยางไว้ที่นิ้วก้อย พันรอบปากถุงหนึ่งรอบ"),
            ("make", {"knot": 1}, 900, "Loop it over the little finger again: that makes the knot.", "คล้องยางกับนิ้วก้อยอีกครั้ง เป็นปม"),
            ("make", {"wraps": 4, "arrows": "spin"}, 1600, "Three more turns round the mouth.", "หมุนยางรัดปากถุงอีกสามรอบ"),
            ("make", {"tuck": 1, "finger": 0, "arrows": ""}, 900, "Tuck the end in at the top edge.", "เหน็บปลายยางไว้ที่ขอบบน"),
            ("hand", {"tuck": 0, "pull": 1, "arrows": "pullend"}, 1000, "Pull the band's end. The knot lets go.", "ดึงปลายยางออก ปมก็คลาย"),
            ("hand", {"wraps": 0, "knot": 0, "pull": 0, "arrows": ""}, 1400, "The turns slacken; slide them off.", "รอบยางหลวม รูดออกได้"),
            ("scis", {"reset": 7, "bowl": 1}, 800, "Scissors: bag in the bowl.", "ใช้กรรไกร ตั้งถุงในชาม"),
            ("scis", dict(BELOW), 900, "Below the band, across the folded neck.", "ตัดใต้ยาง ขวางคอถุงที่พับไว้"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 1000, "The folded mouth comes away with the band.", "ปากถุงที่พับไว้หลุดออกพร้อมยาง"),
        ],
    },
    {
        "id": "tug", "group": "band", "kind": "balloon",
        "en": "Tip folded under: one tug", "th": "พับปลายสอดยาง กระตุกทีเดียว",
        "where_en": "Any banded bag, for a seller who wants you to get in fast.",
        "where_th": "ถุงรัดยางทุกแบบ ร้านที่อยากให้ลูกค้าแกะง่าย",
        "base": {"g": 1, "air": 1, "twist": 1, "level": 168, "contents": "green"},
        "say": ("nan", "One tug! The whole band jumps off!", "กระตุกทีเดียว ยางหลุดทั้งเส้น!"),
        "hand_en": "Tug the tip once.", "hand_th": "กระตุกปลายถุงครั้งเดียว",
        "scis_en": "Cut the band only: one blade under the turns.", "scis_th": "ตัดเฉพาะยาง สอดใบกรรไกรใต้รอบยาง",
        "steps": [
            ("make", {}, 0, "Gather, trap the air, twist, as for the balloon.", "รวบ ขังอากาศ บิดคอ แบบถุงพอง"),
            ("make", {"wraps": 2, "arrows": "spin"}, 1100, "Two turns round the neck.", "พันยางรอบคอสองรอบ"),
            ("make", {"fold": 1, "arrows": ""}, 900, "Fold the tip down beside the neck.", "พับปลายถุงลงแนบคอ"),
            ("make", {"wraps": 4, "over": 2, "arrows": "spin"}, 1200, "The last turns take the neck and the folded tip together.", "รอบสุดท้ายรัดทั้งคอถุงและปลายที่พับไว้"),
            ("hand", {"fold": 0, "drop": 1, "arrows": "tug"}, 700, "Tug the tip up, once, hard. It slides out from under the turns, and they spring loose.", "กระตุกปลายถุงขึ้นแรงๆ ครั้งเดียว ปลายหลุดจากใต้ยาง ยางก็คลายหลุด"),
            ("hand", {"twist": 0, "arrows": ""}, 800, "Untwist and open.", "คลายเกลียวแล้วเปิด"),
            ("scis", {"reset": 3, "bowl": 1}, 800, "Scissors, keeping the bag whole: cut the band, not the plastic.", "ใช้กรรไกรแบบถุงไม่ขาด ตัดยาง ไม่ตัดถุง"),
            ("scis", dict(BANDONLY), 1000, "Slide one blade flat under all the turns, along the neck, point toward the tip. The plastic stays outside the blades.", "สอดใบกรรไกรใบหนึ่งแนบใต้ยางทุกรอบ ตามแนวคอถุง ปลายใบชี้ไปทางปลายถุง ให้พลาสติกอยู่นอกใบกรรไกร"),
            ("scis", {"sc": 0}, 500, "Snip. Every turn is cut at once.", "ตัดฉับเดียว ยางขาดทุกรอบ"),
            ("scis", {"drop": 1, "scis": 0}, 900, "The band falls away and the bag is still sealed by its twist. Untwist over the bowl.", "ยางหลุดร่วง ถุงยังปิดด้วยเกลียว คลายเกลียวเหนือชาม"),
        ],
    },
    {
        "id": "piggyback", "group": "band", "kind": "balloon",
        "en": "Sauce bag riding along", "th": "ถุงน้ำจิ้มฝากมากับถุงใหญ่",
        "where_en": "Soup with its chili, noodles with their vinegar: one band holds both bags.",
        "where_th": "ต้มกับพริก ก๋วยเตี๋ยวกับพริกน้ำส้ม ยางเส้นเดียวรัดสองถุง",
        "base": {"g": 1, "air": 1, "twist": 1, "level": 168, "contents": "soup"},
        "say": ("beer", "Open the big one by hand, and catch the little one when it drops.", "แกะถุงใหญ่ด้วยมือ แล้วรับถุงเล็กที่หล่นไว้ให้ดี"),
        "hand_en": "Roll the lock off, unwind, catch the sauce bag.", "hand_th": "รูดยางล็อกออก คลายรอบ รับถุงน้ำจิ้ม",
        "scis_en": "Band only, so neither bag opens by surprise.", "scis_th": "ตัดเฉพาะยาง ไม่ให้ถุงไหนเปิดเอง",
        "steps": [
            ("make", {}, 0, "Big bag gathered and twisted.", "ถุงใหญ่รวบและบิดคอแล้ว"),
            ("make", {"wraps": 2, "arrows": "spin"}, 1000, "Two turns on its neck.", "พันยางรอบคอสองรอบ"),
            ("make", {"piggy": 1, "arrows": ""}, 1100, "Lay the little sauce bag's twisted neck against the big one's.", "วางคอถุงน้ำจิ้มที่บิดไว้แนบคอถุงใหญ่"),
            ("make", {"wraps": 4, "over": 2, "arrows": "spin"}, 1200, "Keep wrapping: the next turns take both necks.", "พันต่อ รอบต่อไปรัดทั้งสองคอ"),
            ("make", {"lock": 1, "arrows": ""}, 1200, "Lock over the big bag's tip.", "ล็อกข้ามปลายถุงใหญ่"),
            ("hand", {"lock": 2, "arrows": "up"}, 1200, "Roll the lock off the tip.", "รูดยางล็อกออกทางปลาย"),
            ("hand", {"wraps": 0, "pfall": 1, "arrows": "unspin"}, 1500, "Unwind. The sauce bag comes free: catch it.", "คลายยาง ถุงน้ำจิ้มหลุด รับไว้"),
            ("scis", {"reset": 4, "bowl": 1}, 800, "Scissors: if you cut below the band, both bags open at once. Cut the band instead.", "ใช้กรรไกร ถ้าตัดใต้ยาง ถุงจะเปิดทั้งสองใบพร้อมกัน ตัดที่ยางดีกว่า"),
            ("scis", dict(BANDONLY), 1000, "One blade under the turns, along the necks, point to the tip.", "สอดใบกรรไกรใต้รอบยาง ตามแนวคอ ปลายชี้ไปทางปลายถุง"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"drop": 1, "scis": 0, "pfall": 1}, 1000, "Band off, both bags still twisted shut. Open each over its own dish.", "ยางหลุด ทั้งสองถุงยังบิดปิดอยู่ เปิดแต่ละถุงเหนือจานของมัน"),
        ],
    },
    {
        "id": "drink", "group": "band", "kind": "balloon",
        "en": "Drink bag: straw and string", "th": "ถุงน้ำ หลอด เชือกฟาง",
        "where_en": "Iced tea, iced coffee, sugar-cane juice, carried on one finger.",
        "where_th": "ชาเย็น กาแฟเย็น น้ำอ้อย หิ้วนิ้วเดียว",
        "base": {"g": 0, "air": 0, "level": 120, "contents": "tea", "ice": 1},
        "say": ("nan", "The one-finger rule! Everything gets a loop so it hangs off a finger!", "กฎนิ้วเดียว! ทุกอย่างต้องมีห่วงให้หิ้วนิ้วเดียวได้!"),
        "hand_en": "Left tied, you sip. To pour, unwind and pull the straw.", "hand_th": "ไม่ต้องแกะ ดูดเลย จะเทก็คลายยางแล้วดึงหลอด",
        "scis_en": "Below the band, over a jug.", "scis_th": "ใต้ยาง เหนือเหยือก",
        "steps": [
            ("make", {}, 0, "Ice, then the drink, up to the shoulder.", "ใส่น้ำแข็ง แล้วเทเครื่องดื่มถึงไหล่ถุง"),
            ("make", {"g": 1, "air": 0.3, "straw": 1}, 1200, "Gather the mouth round a straw.", "รวบปากถุงรอบหลอด"),
            ("make", {"wraps": 3, "arrows": "spin"}, 1200, "Wind the band round mouth and straw together.", "พันยางรัดปากถุงกับหลอดไว้ด้วยกัน"),
            ("make", {"string": 1, "arrows": ""}, 1200, "A loop of raffia string, tied on under the band, makes the handle.", "ผูกเชือกฟางเป็นห่วงใต้ยาง ไว้หิ้ว"),
            ("hand", {"arrows": "sip"}, 900, "To drink: leave it tied, and sip.", "จะดื่ม ไม่ต้องแกะ ดูดเลย"),
            ("hand", {"string": 0, "wraps": 0, "arrows": ""}, 1300, "To pour it into a glass: slip the string off and unwind the band.", "จะเทใส่แก้ว ถอดเชือกออกแล้วคลายยาง"),
            ("hand", {"straw": 0, "g": 0.6}, 900, "Pull the straw out, open the mouth, pour.", "ดึงหลอดออก เปิดปากถุง เท"),
            ("scis", {"reset": 3, "bowl": 1, "glass": 1}, 800, "Scissors: hold it over a bowl or a jug.", "ใช้กรรไกร ถือถุงไว้เหนือชามหรือเหยือก"),
            ("scis", dict(BELOW, sy=121), 900, "Cut across the neck below the band. The straw gets cut too; that's fine.", "ตัดขวางคอถุงใต้ยาง หลอดขาดไปด้วยก็ไม่เป็นไร"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 1000, "Top off. Pour.", "ปลายถุงหลุด เทได้"),
        ],
    },
    {
        "id": "roll", "group": "band", "kind": "roll",
        "en": "Rolled down, one band round", "th": "ม้วนปากลง รัดยางรอบถุง",
        "where_en": "Dry food: sticky rice, fried snacks, roasted peanuts, khanom.",
        "where_th": "ของแห้ง ข้าวเหนียว ของทอด ถั่วคั่ว ขนม",
        "base": {"contents": "rice"},
        "say": ("beer", "No air, no twist. Flat, so it stacks in a basket.", "ไม่ขังลม ไม่บิด แบนๆ วางซ้อนในตะกร้าได้"),
        "hand_en": "Slide the band off the bottom, unroll.", "hand_th": "รูดยางออกทางก้นถุง แล้วคลี่ม้วน",
        "scis_en": "Snip the band at the side, clear of the bag.", "scis_th": "ตัดยางตรงขอบข้างถุง ห่างจากถุง",
        "steps": [
            ("make", {}, 0, "A flat bag of something dry.", "ถุงแบนใส่ของแห้ง"),
            ("make", {"roll": 1}, 1300, "Roll the top down tight against the food.", "ม้วนปากถุงลงมาจนชิดของข้างใน"),
            ("make", {"band": 1}, 1100, "Stretch one band round the whole bag to hold the roll.", "ดึงหนังยางเส้นเดียวรัดรอบถุงทั้งใบ ให้ม้วนอยู่"),
            ("hand", {"drop": 1, "arrows": "down"}, 1100, "Slide the band down and off the bottom.", "รูดยางลงจนหลุดทางก้นถุง"),
            ("hand", {"roll": 0, "arrows": ""}, 1100, "Unroll.", "คลี่ม้วนออก"),
            ("scis", {"reset": 2}, 600, "Scissors, if the band is too tight to slide:", "ใช้กรรไกร ถ้ายางแน่นจนรูดไม่ออก"),
            ("scis", {"scis": 1, "sx": 418, "sy": 248, "sa": 180, "sc": 1, "slim": 1}, 900, "Slide one blade under the band at the bag's side edge, where it leaves the food.", "สอดใบกรรไกรใต้ยางตรงขอบข้างถุง ตรงที่ยางพ้นของ"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"drop": 1, "scis": 0}, 800, "Band off. Unroll.", "ยางหลุด คลี่ม้วนได้"),
        ],
    },
    {
        "id": "baggie", "group": "band", "kind": "balloon",
        "en": "Sauce baggie, many turns", "th": "ถุงน้ำจิ้ม พันหลายรอบ",
        "where_en": "A spoon of prik nam pla, nam jim, chili vinegar.",
        "where_th": "น้ำปลาพริก น้ำจิ้ม พริกน้ำส้ม ช้อนเดียว",
        "base": {"g": 0, "air": 0, "level": 180, "contents": "namplaprik", "size": 0.62},
        "say": ("nan", "Six turns on a neck as thin as a straw!", "หกรอบ บนคอเล็กเท่าหลอด!"),
        "hand_en": "Push the whole stack up and off the tip.", "hand_th": "ดันยางทั้งกองขึ้นไปหลุดทางปลาย",
        "scis_en": "Snip a bottom corner over the food.", "scis_th": "ตัดมุมก้นถุงเหนืออาหาร",
        "steps": [
            ("make", {}, 0, "A spoon of sauce in a small bag.", "น้ำจิ้มหนึ่งช้อนในถุงเล็ก"),
            ("make", {"g": 1, "air": 1, "twist": 1}, 1100, "Gather, puff, twist. The neck ends up thin as a straw.", "รวบ ขังลม บิดคอ คอถุงเล็กเท่าหลอด"),
            ("make", {"wraps": 6, "arrows": "spin"}, 1800, "So the band goes round many times: five, six, seven.", "ยางจึงต้องพันหลายรอบ ห้า หก เจ็ด"),
            ("make", {"lock": 1, "arrows": ""}, 1100, "Lock over the tip.", "ล็อกข้ามปลายถุง"),
            ("hand", {"lock": 2, "slide": 1, "wraps": 6, "arrows": "up"}, 1400, "Thin neck: pinch the stack of turns and push it up the neck and off the tip, all at once.", "คอถุงเล็ก บีบยางทั้งกองแล้วดันขึ้นตามคอ หลุดออกทางปลายทีเดียว"),
            ("hand", {"twist": 0, "arrows": ""}, 700, "Untwist over the food.", "คลายเกลียวเหนืออาหาร"),
            ("scis", {"reset": 3}, 600, "Scissors: hold it over the plate.", "ใช้กรรไกร ถือเหนือจาน"),
            ("scis", {"scis": 1, "sx": 356, "sy": 356, "sa": -140, "sc": 1, "slim": 1}, 900, "Snip a bottom corner: 2 to 3 mm for runny sauce like prik nam pla, 5 mm or more for thick sweet chili.", "ตัดมุมก้นถุง 2-3 มม. สำหรับน้ำจิ้มใสอย่างน้ำปลาพริก 5 มม. ขึ้นไปสำหรับน้ำจิ้มข้นอย่างน้ำจิ้มไก่"),
            ("scis", {"sc": 0, "corner": 1}, 500, "Snip.", "ตัด"),
            ("scis", {"pour": 1, "scis": 0}, 1400, "Squeeze it out like icing. The band never has to come off.", "บีบออกเหมือนบีบครีม ไม่ต้องแกะยางเลย"),
        ],
    },
    {
        "id": "overhand", "group": "plain", "kind": "knot",
        "en": "Knot in the bag itself", "th": "ผูกปมที่ปากถุง",
        "where_en": "Fruit, vegetables, ice, small sauce bags: no band at all.",
        "where_th": "ผลไม้ ผัก น้ำแข็ง ถุงน้ำจิ้มใบเล็ก ไม่ใช้ยาง",
        "base": {"k": 0, "contents": "ice"},
        "say": ("beer", "Too tight? Twist the knot and the tail against each other, then wiggle.", "แน่นเกิน? บิดปมกับหางถุงสวนกัน แล้วโยกๆ"),
        "hand_en": "Push the tail back into the knot, then work the tip out.", "hand_th": "ดันหางกลับเข้าปมให้หลวม แล้วค่อยๆ ดึงปลายออก",
        "scis_en": "Across the neck, below the knot.", "scis_th": "ขวางคอถุง ใต้ปม",
        "steps": [
            ("make", {}, 0, "Gather the mouth and twist it into a tail.", "รวบปากถุง บิดให้เป็นหาง"),
            ("make", {"k": 1}, 1100, "Bend the tail round into a loop.", "งอหางถุงวนเป็นห่วง"),
            ("make", {"k": 2}, 1100, "Push the tip through the loop.", "สอดปลายถุงผ่านห่วง"),
            ("make", {"k": 3, "arrows": "pullknot"}, 1000, "Pull the tip. The knot closes down onto the bag.", "ดึงปลาย ปมรูดลงมาชิดถุง"),
            ("hand", {"k": 2.2, "arrows": "push"}, 1200, "Pinch the knot and push the tail back into it. It loosens.", "บีบปม ดันหางกลับเข้าไป ปมจะหลวม"),
            ("hand", {"k": 1, "arrows": ""}, 1100, "Work the tip back out through the loop.", "ค่อยๆ ดึงปลายออกจากห่วง"),
            ("hand", {"k": 0}, 900, "Straighten the tail and open.", "คลี่หางแล้วเปิด"),
            ("scis", {"reset": 3}, 600, "Scissors: bag upright.", "ใช้กรรไกร ตั้งถุงตรง"),
            ("scis", {"scis": 1, "sx": 120, "sy": 88, "sa": 0, "sc": 1}, 900, "Across the neck, just below the knot.", "ขวางคอถุง ใต้ปมนิดเดียว"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 1000, "Knot off, bag open.", "ปมหลุด ถุงเปิด"),
        ],
    },
    {
        "id": "double", "group": "plain", "kind": "handles",
        "en": "Carrier bag, double knot", "th": "ถุงหูหิ้ว ผูกสองชั้น",
        "where_en": "The market bag of fruit or groceries.",
        "where_th": "ถุงหิ้วใส่ผลไม้ ของจากตลาด",
        "base": {"h": 0, "contents": "fruit"},
        "say": ("nan", "Mangoes! We stopped for mangoes!", "มะม่วง! แวะซื้อมะม่วง!"),
        "hand_en": "Push both handles in toward the knot, then pick it apart.", "hand_th": "ดันหูทั้งสองเข้าหาปมให้หลวม แล้วแกะ",
        "scis_en": "Snip one handle beside the knot.", "scis_th": "ตัดหูข้างหนึ่งข้างปม",
        "steps": [
            ("make", {}, 0, "A carrier bag (ถุงหูหิ้ว), full.", "ถุงหูหิ้ว ใส่ของเต็ม"),
            ("make", {"h": 1}, 1000, "Cross the handles.", "ไขว้หูถุง"),
            ("make", {"h": 2}, 1000, "Tie them once.", "ผูกหนึ่งครั้ง"),
            ("make", {"h": 3}, 1000, "Tie again on top. A double knot.", "ผูกซ้ำทับอีกครั้ง เป็นปมสองชั้น"),
            ("hand", {"h": 2.3, "arrows": "pushh"}, 1100, "Push both handles in toward the knot to give it slack.", "ดันหูทั้งสองเข้าหาปม ให้ปมหลวม"),
            ("hand", {"h": 1, "arrows": ""}, 1000, "Pick the top knot open, then the bottom one.", "แกะปมบนออก แล้วแกะปมล่าง"),
            ("hand", {"h": 0}, 800, "Handles apart.", "หูถุงแยกออก"),
            ("scis", {"reset": 3}, 600, "Scissors:", "ใช้กรรไกร"),
            ("scis", {"scis": 1, "sx": 120, "sy": 120, "sa": 0, "sc": 1}, 900, "Snip one handle, just beside the knot.", "ตัดหูถุงข้างหนึ่ง ชิดปม"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 1000, "The knot comes off with one handle; the bag opens.", "ปมหลุดไปกับหูข้างหนึ่ง ถุงเปิด"),
        ],
    },
    {
        "id": "bow", "group": "plain", "kind": "handles",
        "en": "Carrier bag, bow", "th": "ถุงหูหิ้ว ผูกโบว์",
        "where_en": "Same bag, for someone who will open it again soon.",
        "where_th": "ถุงเดียวกัน สำหรับคนที่จะเปิดอีกเร็วๆ นี้",
        "base": {"h": 0, "contents": "fruit"},
        "say": ("beer", "Pull the loose end, the bow's gone. No scissors needed.", "ดึงปลายเดียว โบว์หลุด ไม่ต้องใช้กรรไกร"),
        "hand_en": "Pull the loose end.", "hand_th": "ดึงปลายที่ห้อยอยู่",
        "scis_en": "Not needed.", "scis_th": "ไม่ต้องใช้",
        "steps": [
            ("make", {}, 0, "Carrier bag, full.", "ถุงหูหิ้ว ใส่ของเต็ม"),
            ("make", {"h": 1}, 1000, "Cross the handles.", "ไขว้หูถุง"),
            ("make", {"h": 2}, 1000, "Tie once.", "ผูกหนึ่งครั้ง"),
            ("make", {"bow": 1}, 1100, "Second tie with a loop folded into one handle: a bow, one end left loose.", "ผูกครั้งที่สองโดยพับหูข้างหนึ่งเป็นห่วง เป็นโบว์ เหลือปลายหนึ่งห้อยไว้"),
            ("hand", {"bow": 0, "arrows": "pullbow"}, 900, "Pull the loose end. The bow undoes in one pull.", "ดึงปลายที่ห้อยอยู่ โบว์หลุดในทีเดียว"),
            ("hand", {"h": 0, "arrows": ""}, 1000, "Undo the first tie.", "แกะปมแรก"),
        ],
    },
    {
        "id": "seal", "group": "plain", "kind": "flat",
        "en": "Heat seal", "th": "ซีลด้วยความร้อน",
        "where_en": "Sauce sachets, an onsen egg's sauce, drinks sealed in a cup.",
        "where_th": "ซองซอส ซอสไข่ออนเซ็น แก้วน้ำที่ซีลฝา",
        "base": {"style": "seal", "contents": "soy"},
        "say": ("nan", "The onsen egg's sauce! Tear at the little notch!", "ซอสไข่ออนเซ็น! ฉีกตรงรอยบาก!"),
        "hand_en": "Tear at the notch.", "hand_th": "ฉีกตรงรอยบาก",
        "scis_en": "Straight across, just under the seal.", "scis_th": "ตัดตรงใต้รอยซีล",
        "steps": [
            ("make", {}, 0, "Sauce in a flat bag, mouth open.", "ซอสในถุงแบน ปากยังเปิด"),
            ("make", {"jaw": 1}, 900, "The sealer's hot bars close on the mouth.", "แท่งร้อนของเครื่องซีลหนีบปากถุง"),
            ("make", {"jaw": 0, "seal": 1}, 900, "The plastic melts together in a ribbed strip.", "พลาสติกละลายติดกันเป็นแถบลาย"),
            ("hand", {"tear": 1, "arrows": "tear"}, 1100, "Tear at the notch, if it has one. Hold it upright.", "ฉีกตรงรอยบาก ถ้ามี ถือตั้งไว้"),
            ("scis", {"reset": 2}, 600, "No notch:", "ไม่มีรอยบาก"),
            ("scis", {"scis": 1, "sx": 100, "sy": 122, "sa": 0, "sc": 1}, 900, "Scissors straight across, just under the seal.", "ตัดตรงๆ ใต้รอยซีล"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 900, "Open.", "เปิดแล้ว"),
        ],
    },
    {
        "id": "staple", "group": "plain", "kind": "flat",
        "en": "Folded and stapled", "th": "พับแล้วเย็บแม็ก",
        "where_en": "Pork crackling, crisps, dried fruit, with a paper label on top.",
        "where_th": "แคบหมู ขนมกรอบ ผลไม้อบแห้ง มีป้ายกระดาษ",
        "base": {"style": "staple", "contents": "crackling"},
        "say": ("beer", "Leave the staple. Tear below it.", "ไม่ต้องแกะลวด ฉีกใต้ป้าย"),
        "hand_en": "Tear the plastic below the label.", "hand_th": "ฉีกถุงใต้ป้าย",
        "scis_en": "Straight across, under the label.", "scis_th": "ตัดตรงใต้ป้าย",
        "steps": [
            ("make", {}, 0, "A bag of pork crackling (แคบหมู).", "แคบหมูหนึ่งถุง"),
            ("make", {"folds": 2}, 1000, "Fold the top over twice.", "พับปากถุงลงสองทบ"),
            ("make", {"label": 1}, 900, "A folded paper label goes over the top.", "สวมป้ายกระดาษพับครอบปากถุง"),
            ("make", {"staple": 1}, 700, "One or two staples through all of it.", "เย็บแม็กหนึ่งสองตัว ทะลุทั้งหมด"),
            ("hand", {"tear": 1, "arrows": "tear"}, 1100, "Tear the plastic just below the label. Staples stay put; no prising.", "ฉีกถุงตรงใต้ป้าย ลวดแม็กอยู่ที่เดิม ไม่ต้องงัด"),
            ("scis", {"reset": 3}, 600, "Scissors:", "ใช้กรรไกร"),
            ("scis", {"scis": 1, "sx": 100, "sy": 150, "sa": 0, "sc": 1}, 900, "Straight across, just under the label.", "ตัดตรงๆ ใต้ป้าย"),
            ("scis", {"sc": 0}, 500, "Snip.", "ตัด"),
            ("scis", {"sever": 1, "scis": 0}, 900, "Label, staples and folds come off together.", "ป้าย ลวด และรอยพับ หลุดออกไปด้วยกัน"),
        ],
    },
]


def js_data(lang):
    out = []
    for t in TIES:
        out.append({"id": t["id"], "kind": t["kind"], "base": t["base"],
                    "steps": [{"p": p, "s": s, "ms": ms, "t": (en if lang == "en" else th)} for (p, s, ms, en, th) in t["steps"]]})
    return out
